# Generated by Django 2.0 on 2019-05-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateDimension',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('en_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ch_name', models.CharField(max_length=100)),
                ('short_ch_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_time_raw', models.CharField(max_length=100)),
                ('waiting_time', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DateDimension')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hospital')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='waitingtime',
            unique_together={('date', 'hospital')},
        ),
    ]
