# Generated by Django 2.0 on 2019-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190526_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingtime',
            name='waiting_time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
